import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import FooterComponent from '../components/Footer';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Catalog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Catalog App</h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>UI companies &rarr;</h2>
            <Link href="/companies/">
              <a>Construction companies</a>
            </Link>
          </div>

          <div className={styles.card}>
            <h2>API companies &rarr;</h2>
            <Link href="/api/companies">
              <a>Construction companies</a>
            </Link>
          </div>
        </div>
      </main>

      <FooterComponent />
    </div>
  );
};

export default Home;
